krasaVoVrecku/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('landing.urls')),
    path('krasavovrecku/feed/', include('mainfeed.urls')),
    path('directmessages/', include('directmessages.urls')),
    path('questions/', include('question.urls')),
    path('booking/', include('booking.urls')),
    path('users/api/', include('users.api.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

question/urls.py
from django.urls import path
from .views import Questions, QuestionView, CreateQuestion, UpdateQuestion, DeleteQuestion, DeleteMesage

urlpatterns = [
    path('', Questions.as_view(), name='home'),
    path('question/<str:pk>/', QuestionView.as_view(), name='question'),
    path('create-questin/', CreateQuestion.as_view(), name="create-question"),
    path('update-questin/<str:pk>/', UpdateQuestion.as_view(), name="update-question"),
    path('delete-question/<str:pk>/', DeleteQuestion.as_view(), name="delete-question"),
    path('delete-message/<str:pk>/', DeleteMesage.as_view(), name="delete-message"),
]

users/urls.py
from django.urls import path
from django.views import View
from .views import Dashboard, Register, ProfileView, ProfileEditView



urlpatterns = [

    path('dashboard/', Dashboard.as_view(), name="dashboard"),
    path('register/', Register.as_view(), name="register"),
    path('profile/<str:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>', ProfileEditView.as_view(), name='profile-edit'),
]

question/models.py
from django.db import models
from django.contrib.auth.models import User


def getcurrenthostname(instance, filename):
    return "uploads/questions/{0}/{1}".format(instance.host.username, filename)

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Question(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to=getcurrenthostname, default='uploads/profilepictures/default.png',
                                        blank=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']


    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

# Create your models here.

question/forms.py
from django.forms import ModelForm
from .models import Question

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        exclude = ['host', 'participants']

question/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.views import View
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from .models import Question, Topic, Message
from .forms import QuestionForm


class Questions(View):
	def get(self, request, *args, **kwargs):
	    q = request.GET.get('q') if request.GET.get('q') != None else ''
	    questions = Question.objects.filter(
	        Q(topic__name__icontains=q) |
	        Q(name__icontains=q) |
	        Q(description__icontains=q)
	    )

	    topics = Topic.objects.all()
	    questions_count = questions.count()
	    feeds = Message.objects.filter(Q(question__topic__name__icontains=q)).order_by('-created')

	    context = {'questions': questions, 'topics': topics, 'questions_count': questions_count, 'feeds': feeds}
	    return render(request, 'questions.html', context)


class QuestionView(View):
	def get(self, request, pk, *args, **kwargs):
	    question = Question.objects.get(id=pk)
	    question_messages = question.message_set.all().order_by('-created')
	    participants = question.participants.all()

	    context = {'question': question, 'question_messages': question_messages, 'participants': participants}
	    return render(request, 'question.html', context)

	def post(self, request, pk, *args, **kwargs):
		question = Question.objects.get (id=pk)

		message = Message.objects.create (
			user=request.user,
			question=question,
			body=request.POST.get ('body')
		)
		question.participants.add (request.user)
		return redirect ('question', pk=question.id)


class CreateQuestion(View):
	def get(self, request, *args, **kwargs):
		form = QuestionForm()
		topics = Topic.objects.all()

		context = {'form': form, 'topics': topics}
		return render (request, 'question_form.html', context)

	def post(self, request, *args, **kwargs):

		topic_name = request.POST.get ('topic')
		topic, created = Topic.objects.get_or_create (name=topic_name)
		Question.objects.create (
			host=request.user,
			topic=topic,
			name=request.POST.get ('name'),
			description=request.POST.get ('description')
		)
		return redirect ('home')


class UpdateQuestion(View):
	def get(self, request, pk, *args, **kwargs):
		question = Question.objects.get (id=pk)
		form = QuestionForm (instance=question)
		topics = Topic.objects.all ()

		if request.user != question.host:
			return HttpResponse ('You dont have the authorisation to update question!')

		context = {'form': form, 'topics': topics, 'question': question}
		return render (request, 'question_form.html', context)

	def post(self, request, pk, *args, **kwargs):
		question = Question.objects.get (id=pk)
		topic_name = request.POST.get ('topic')
		topic, created = Topic.objects.get_or_create (name=topic_name)
		question.name = request.POST.get ('name')
		question.topic = topic
		question.description = request.POST.get ('description')
		question.save ()
		return redirect ('home')


class DeleteQuestion(View):
	def get(self, request, pk, *args, **kwargs):
		question = Question.objects.get(id=pk)

		if request.user != question.host:
			return HttpResponse ('You dont have the authorisation to update question!')

		return render (request, 'delete.html', {'obj': question})

	def post(self, request, pk, *args, **kwargs):
		question = Question.objects.get (id=pk)
		question.delete ()
		return redirect ('home')

class DeleteMesage(View):
	def post(self, request, pk, *args, **kwargs):
		message = Message.objects.get (id=pk)

		if request.user != message.user:
			return HttpResponse ('You dont have the authorisation to update question!')

		if request.method == 'POST':
			message.delete ()
			return redirect ('home')
		return render (request, 'delete.html', {'obj': message})

question/templates/activity_component.html
<h3>Recent Activity</h3>
<hr>
{% for feed in feeds %}
<div>
    <small><a class="btn-outline-dark" href="{% url 'profile' feed.user.id %}">@{{feed.user}}</a>  {{feed.created|timesince}} ago </small>
    <small>replied to "{{feed.question}}"</small>

    <p>{{feed}}</p>
    {% if request.user == message.user %}
    <a href="{% url 'delete-feed' feed.id %}">Delete</a>
    {% endif %}
    <hr>
</div>
{% endfor %}

question/templates/delete.html
{% extends 'landing/base.html' %}

{% block content%}
<div class="home-container">
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-20 col-sm-10">
                <form method="POST" action="">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{obj}}"?</p>

                    <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
                    <input type="submit" value="Confirm" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

question/templates/feed_component.html
{% for question in questions %}
<div>
    {% if request.user == question.host %}
    <a class="btn-outline-dark" href="{% url 'update-question' question.id %}">Edit</a>
    <a class="btn-outline-dark" href="{% url 'delete-question' question.id %}">Delete</a>
    {% endif %}
    <a class="btn-outline-dark" href="#">@{{question.host.username}}</a>
    <h5><a class="btn-outline-dark" href="{% url 'question' question.id %}">{{question.name}}</a></h5>
    <small>{{question.topic.name}}</small>
    <hr>
</div>
{% endfor %}

question/templates/question.html
{% extends 'landing/base.html' %}
{% block content %}
<style>
    .question-container{
        display: grid;
        grid-template-columns: 3fr 1fr;
    }
    .question{
        display: grid;
        grid-template-columns: 3fr 1fr,
    }

</style>
<div class="question-container">
    <div class="container">
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'home' %}" class="btn btn-light">Naspat na Otazky</a>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-md-20 col-sm-10">
                <div class="question">
                    <h2>{{question.name}}</h2>
                    <div>
                        <span><p>Asked By</p>
                            <a class="btn-outline-dark" href="{% url 'profile' question.host.id %}" class="question">
                                <div class="avatar avatar--small">
                                    <img class="round-circle post-img" height="30" width="30" src="{{ question.host.profile.profilepicture.url }}" /><span>@{{question.host.username}}</span>
                                </div>
                        </a></span>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6"><span>
                    <img height="200" width="200" src="{{ question.image.url }}" />
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-20 col-sm-10">
                <div class="question">
                    <span class="question_topics">{{question.topic}}</span>
                    {% if question.host == request.user %}
                    <div>
                        <div>
                            {% if request.user == question.host %}
                            <a class="btn-outline-dark" href="{% url 'update-question' question.id %}">Edit</a>
                            <a class="btn-outline-dark" href="{% url 'delete-question' question.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-20 col-sm-10">

                {% endif %}
                <p>{{question.description}}</p><span>{{question.created|timesince}} ago</span>

                <div class="comment-wrapper">
                    <h3>Odpovede</h3>
                    <hr>

                    {% for message in question_messages %}
                    <div>
                        {% if request.user == message.user %}
                        <a class="btn-outline-dark" href="{% url 'delete-message' message.id %}">Delete</a>
                        {% endif %}
                        <smal>
                            <a class="btn-outline-dark" href="{% url 'profile' message.user.id %}" class="comment-wrapper">@{{message.user}}</a>{{message.created|timesince}} ago </smal>
                        <p>{{message.body}}</p>
                        <hr>
                    </div>
                    {% endfor %}
                </div>
                {% if request.user.is_authenticated %}
                <div class="comment-form">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <input type="text" name="body" placeholder="Write your message here..."/>
                    </form>
                </div>
                {% endif %}
            </div>
         </div>
    </div>
    <div class="container">
        <div class="row justify-content-center mt-1">
            <div class="col-md-20 col-sm-10">

                <div class="participants">
                    <h3 class="participants__top">Participants <span>{{participants.count}}</span></h3>
                    {% for user in participants %}
                        <div>
                            <a class="btn-outline-dark" href="{% url 'profile' user.id %}" class="particiipant">@{{user.username}}</a>
                            <p>

                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
         </div>
     </div>
</div>
{% endblock content %}

question/templates/question_form.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="home-container">
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-3 col-sm-6">
                <a href="{% url 'home' %}" class="btn btn-light">Naspat na Otazky</a>
            </div>
        </div>
        <div class="row justify-content-center mt-5">
            <div class="col-md-20 col-sm-10">
                <div class="layout__body">
                    <form class="form" method="POST" action="">
                        {% csrf_token %}
                        <div class="row justify-content-center mt-5">
                            <div class="form__group">
                                <label for="question_topic">Enter a Topic</label>
                                <input required type="text" value="{{question.topic.name}}" name="topic" list="topic-list" />
                                <datalist id="topic-list">
                                    <select id="question_topic">
                                        {% for topic in topics %}
                                        <options value="{{topic.name}}">{{question.name}}</options>
                                        {% endfor %}
                                    </select>
                                </datalist>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-md-3 col-sm-6">
                                <div class="form__group" enctype="multipart/form-data">
                                    <label for="question_image">Obrazok</label>
                                    {{form.image}}
                                </div>
                            </div>
                        </div>
                        <div class="row mt-5">
                            <div class="col-md-3 col-sm-6">
                                <div class="form__group">
                                    <label for="question_name">Question</label>
                                    {{form.name}}
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center mt-5">
                            <div class="form_group">
                                <label for="room_name">Question Description</label>
                                <div class="row justify-content-center mt-5">
                                    {{form.description}}
                                    <div>
                            </div>
                        </div>
                                <br>

                        <input class="btn btn-outline-dark" type="submit" value="Submit" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content%}

question/templates/questions.html
{% extends 'landing/base.html' %}
{% block content %}

<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }

</style>

<div class="home-container">
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-20 col-sm-10">
                <div>
                    {% include 'topics_component.html' %}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row mt-5">
            <div class="col-md-6 col-sm-10">
                <h5>Opitanich Otazok: {{questions_count}} </h5>
                <a href="{% url 'create-question' %}">create question</a>
                <br>
                {% include 'feed_component.html' %}
                <br>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row mt-5">
            <div class="col-md-20 col-sm-10">
                {% include 'activity_component.html' %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

question/templates/topics_component.html
<h3>Browse Topics</h3>
<hr>

<div>
    <a class="btn-outline-dark" href="{% url 'home' %}">All</a>
</div>

{% for topic in topics %}
<div class="Topics">
    <a class="btn-outline-dark" href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}</a>
    <spam>{{topic.question_set.all.count}}</spam>
</div>
{% endfor %}